spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/qg?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        use_sql_comments: true
