volumes:
  db:

services:
  db:
    container_name: qg-db
    image: mysql:8.0.38
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: qg
      MYSQL_ROOT_PASSWORD: root
      LANG: C.UTF-8
      TZ: Asia/Seoul
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
